set echo on;

create table USERDETAILS (
    USERID VARCHAR2(255 BYTE) not null,
    USERIDNUMBER VARCHAR(13) not null,
    USERNAME VARCHAR2(255 BYTE) not null,
    USERLNAME VARCHAR2(255 BYTE) not null,
    USERCELLNUM VARCHAR(10) not null,
    USERAGE NUMBER(2),
    USERGENDER VARCHAR(10),
    PRIMARY KEY (USERID)
);

create table ACCOUNTTYPE (
    TYPEOFACCOUNT VARCHAR2(255 BYTE) not null,
    REWARDSKEY NUMBER not null,
    PRIMARY KEY (TYPEOFACCOUNT)
);

create table REWARDSTORE (
    AMTGAINED NUMBER,
    MULTIPLIER NUMBER,
    POINTSPENT NUMBER,
    CURRENTAMT NUMBER
);

commit;

DROP TABLE AFFECTED_LGA;
DROP TABLE ASSESSOR_EMPLOYMENT_HISTORY;
DROP TABLE INSURANCE_ASSESSOR;
DROP TABLE INSURANCE_COMPANY;
DROP TABLE LOCAL_GOVERNMENT_AREA;
DROP TABLE SECONDARY_EVENT;
DROP TABLE FIRE_EVENT;
DROP TABLE PROPERTY;
DROP TABLE P_OWNER;
DROP TABLE PROPERTY_TYPE;
DROP TABLE CHILDREN;
DROP TABLE UNIT_GOOD;
DROP TABLE STUDENT_POOR;
DROP TABLE STUDENT_GOOD;
DROP TABLE STUDENT;
DROP TABLE REWARDSTORE;
DROP TABLE SCHEDCLASS;
DROP TABLE PREREQ;
DROP TABLE ENROLMENT;
DROP TABLE STAFF;
DROP TABLE OFFERING;
DROP TABLE UNIT;
COMMIT;

DROP TABLE JOBS;
DROP TABLE LOCATIONS;
DROP TABLE REGIONS;
DROP TABLE COUNTRIES;
DROP TABLE DEPARTMENTS;
DROP TABLE EMPLOYEES;
commit;

ALTER TABLE USERDETAILS
    ADD USERID VARCHAR2(255 BYTE) not null;
ALTER TABLE USERDETAILS
    ADD USERIDNUMBER VARCHAR(13) not null;
ALTER TABLE USERDETAILS
    DROP PRIMARY KEY ;
ALTER TABLE USERDETAILS
    ADD PRIMARY KEY (USERID);